name: PR Workflow

on:
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "always"
          #skip_after_successful_duplicate: "true"
          #paths_ignore: '["**/README.md", "**/docs/**"]'
          #do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  check_skip_condition:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip = 'true'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  actual_job:
    runs-on: ubuntu-latest
    needs: pre_job
    steps:
      - run: echo "Sleeping for 3 minutes..." && sleep 180
